#+Title: NixOS training material
#+Author: Katharina Fey
#+SETUPFILE: html.setup

  Welcome to my Nix training material repository.  I created this
  material with the purpose of having a set of slides, code examples,
  example projects, and advanced visualisations to teach the Nix
  expression language and ecosystem to developers of varying
  backgrounds.

  Is your company looking for trainings?  [[mailto:kookie@spacekookie.de][Contact me]] for details and
  booking!

* Outline

   This repository is structured as a set of course trees.  Each tree
   focuses on conveying a single aspect of the Nix ecosystem.  Each
   course tree should take between 2-4 hours to teach.  Following is
   an overview of available courses.

   - [[./courses/01-introduction/README.org][Introduction to Nix]] :: A general introduction to the Nix
     ecosystem, the theoretical mechanisms that are required to make
     it work, and an outline of what problems Nix solves
   - [[./courses/02-modules/README.org][NixOS module system]] :: A deep-dive into the Nix module system,
     NixOS configuration principles and designing module abstractions
   - [[./courses/03-cross/README.org][Cross compilation]] :: An excursion into doing cross-compilation
     with Nix

* Building these slides

   The slides are written in [org-mode], a plain-text markup language.
   As such it is very easy to read and adapt in any text editor.
   GitHub and GitLab are able to render the documents, but not as
   slide decks.  There is currently no hosted version of the slides
   available.

   To build the slides you will need emacs with ~org-mode~ installed.
   You can include the ~ci/export-course.el~ file and then run
   ~export-course~ in the directory of any of the sub-courses to
   generate the slide decks.

* Sponsors

   This course has been sponsored by various companies that have paid
   for trainings and the creation of new material in the past.

   (todo: insert logos)
   

* License

   This workshop material is licensed CC-BY-SA.
