#+Title: NixOS workshop material
#+Author: Katharina Fey
#+SETUPFILE: html.setup

  Welcome to the Nix teaching material repository.  This material was
  created by [[file:into.org][Katharina Fey]] with the purpose of having a set of slides,
  code examples, example projects, and advanced visualisations to
  teach the Nix expression language and ecosystem to developers of
  varying backgrounds.

  Is your company looking for teaching?  [[mailto:kookie@spacekookie.de][Contact me]] for details and
  booking!

* Outline

   This repository is structured as a set of course trees.  Each tree
   focuses on conveying a single aspect of the Nix ecosystem.  Each
   course tree should take between 2-4 hours to teach.  Following is
   an overview of available courses.

   - [[./courses/01-introduction/README.org][Introduction to Nix]] :: A general introduction to the Nix
     ecosystem, the theoretical mechanisms that are required to make
     it work, and an outline of what problems Nix solves
   - [[./courses/02-modules/README.org][NixOS module system]] :: A deep-dive into the Nix module system,
     NixOS configuration principles and designing module abstractions
   - [[./courses/03-cross/README.org][Cross compilation]] :: An excursion into doing cross-compilation
     with Nix

* Building these slides

   These slides are built with ~org-mode~ and ~elisp~.

* License

   This workshop material is licensed CC-BY-SA.
